name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Linode
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server_ip << 'EOF'
            cd /home/user/adventra
            git pull origin main
            npm install
            npm run build
            pm2 restart adventra || pm2 start npm --name "adventra" -- start
          EOF
